### ISSUE TITLE
Request for more configs

### ISSUE THREAD

**Issue by HanatakeYurii** [Xericore/EasyCarts#1]
Hi,

First let me say that I love your plugin. I've been using it for a long time on my server, it goes well.

Due to the large amount of players I encounter on my server, I had to find ways to reduce ram et cpu consuming, and one of these ways was to do something about abandoned boats and minecarts.

For this I use a plugin called AutoMinecarts that let me spawn carts and boats that disappear when the player goes off. Keep in mind that they don't have to craft them since it's automatically spawned.

The problem I encounter is that when a player use these carts on a intersection, they are replaced by a regular one that don't despawn but more that drop, making it exploit and in a way ruining the economy. In the other way I want players to be able to use regular carts in their regions, so I can't set RemoveMinecartOnExit to true, they would lost them.

So my only hope would be a config option to disable intersection holding, and if possible another one to disable left clicking caucing to stop (we have a huge rail network and having players stopping in the middle is really annoying for followers).

So, please, can you add theses?

PS: I would like to ask you if "push entities" always work or not. I saw somewhere it could be speed related. My perfect goal would be to totally ignore minecart collisions with entities, so pass through, but always pushing them could do the work.

**Comment by Xericore** [comment]
Hi,
I'm glad you like my plugin. 
Instead of AutoMinecarts, you could use CraftBook and enable the MinecartTemporaryCart feature. This allows you to right click a rail with an empty hand to instantly spawn a minecart. Just make sure to setRemoveMinecartOnExit: true in config.yml to correctly remove carts when doing so.
I also suggest you don't allow players to sell minecarts to the server.

The intersection feature is a core element of EasyCarts and unfortunately I cannot remove it.
My suggestion is to make minecarts free (only normal minecarts). Players can spawn a normal minecart any time they right click a normal rail with an empty hand. And every time they exit, the cart gets destroyed. This works best on my server.

Push entities should always work, but under certain circumstances the event might be fired too late. I've optimized that method in EasyCarts 1.7. Please try it and tell me if it works better on your server now.
I've also added the config StopStartOnLeftClick in EasyCarts 1.7. Just set it to false any players won't be able to stop by left clicking anymore.

Hope this helps

**Comment by HanatakeYurii** [comment]
Hi,
Thanks for the response, unfornately we tried craftbook some weeks ago but it cannot work properly on our server. It's dependency ProtocolLib is buggy, so we cannot use it. 
Instead, AutoMinecarts does exactly what you described: right-clicking on a rail spawn the player in a minecart that will disappear if he goes off. It's not possible possible for us to disable minecarts selling, and would be against our rules.

Too bad you can't disable that behavior by config. We will try using setRemoveMinecartOnExit for a time but if it annoys community, we'll have to go for another way. 

Thanks for the 1.7, I will try it and tell you.

**Comment by HanatakeYurii** [comment]
I'm back,

I tried 1.7 and it works really well. 
I thought about my system, and I come up with an idea:
would it be possible to prevent players to place empty minecarts (not the chest or the hopper versions)?

In fact I want my players to be able to use minecarts variants (not regular), For this I cannot disable the crafting recipe of the since they're required to craft variants. In addtition players remain able to find minecarts in dungeons and minecshafts. 

So it would be perfect if they were unable to place minecarts. They could only use temporary carts.

Hope you can do something. But if not, it would not be a big harm.
Also thanks for reading and for the help

**Comment by Xericore** [comment]
Hi Yurii,
I'm sure that it would be possible to write a plugin that disables the placement of normal minecarts. However, I don't think that this is something that should be added to EasyCarts, since it doesn't seem like a feature that many people will need. Plus, I don't know exactly what those "minecart variants" are. Are they made with custom crafting recipies/mods or do you mean chest/hopper/powered etc. carts?
Sorry that I can't help you out in every aspect, but I can only add features that will benefit at least a couple of servers.

**Comment by HanatakeYurii** [comment]
Hi,
Thanks for responding,
For "minecarts variants", I mean chest/hopper/tnt... carts. 
You're right, that features would not be used by many people and would not fit really well in your plugin. 
Unfortunately, my players need "empty" carts for other user than player transportation, and since you can't add a config to disable intersections I will sadly have to use another plugin.

Anyway thanks for your time and help

(A last thought: if at intersections the minecart was moved/TP to the right place instead of destroying it and spawning the player in another one that lacks the specs of the first, this would solve itself, but I really don't if it's possible. I would suppose to, but I'm not sure.)
