### ISSUE TITLE
1.14 Update?

### ISSUE THREAD

**Issue by Benjamming101** [Xericore/EasyCarts#11]
Hi, I don't know how to use github but I'm hoping this is the right place to ask about this. I'm curious if there are any plans for a 1.14 update? Thanks!

**Comment by Xericore** [comment]
Hi, version 1.13.2 should work on 1.14 without any problems. But yes, there will be an official update for 1.14 and 1.15 as well. I am working on a large update that will support driving quickly on diagonal rails.

**Comment by yashendra2797** [comment]
Any progress?

**Comment by Xericore** [comment]
Yes there's been some progress. I have a semi-working beta of EasyCarts 2.0 that supports fast driving on diagonal rails. There's still a bug in there that boosting on golden rails doesn't work properly.
If you don't need fast driving on diagonal rails just pick the latest EasyCarts 1.13.2 from spigotmc. It works fine on Minecraft 1.14 and 1.15. Unfortunately I don't know when I'll have time to fix the 2.0 bug to release it because I have very little time for it right now :/

**Comment by yashendra2797** [comment]
That's alright man. Take care of yourself!

**Comment by Xericore** [comment]
I've just released EasyCarts 2.1. This version is built against the Spigot 1.13.2 API and will work fine on 1.13 - 1.16. Note that this version does not yet contain the new feature that allows driving quickly on diagonal rails. That will be in EasyCarts 3.0.
